"""Agent Converter (Mock)

将 JSON 配置转换为 Python 文件 (统一输出 echo server)
"""

import tempfile
from pathlib import Path
from typing import Dict, Any


class AgentConverter:
    """Agent 配置转换器 (Mock - 统一输出 echo server)"""

    async def convert_to_python(
        self,
        config_json: Dict[str, Any],
        name: str,
        output_dir: str,
    ) -> str:
        """
        将 JSON 配置转换为 Python 文件

        无论输入什么 JSON，统一输出一个 echo server Python 文件

        Args:
            config_json: JSON 配置（会被忽略）
            name: 包名
            output_dir: 输出目录

        Returns:
            生成的 Python 文件路径
        """
        # 使用固定文件名，避免中文名导致 build 工具解析错误
        output_path = Path(output_dir) / "agent.py"

        # Hello server 模板
        python_content = f'''"""Hello Agent - Auto-generated by AgentConverter"""

import argparse
import uvicorn
from fastapi import FastAPI
from fastapi.responses import JSONResponse

app = FastAPI(title="{name}", version="1.0.0")


@app.get("/")
async def root():
    """根路径 - Hello 接口"""
    return JSONResponse({{"message": "Hello from {name}!"}})


def main():
    """主函数"""
    parser = argparse.ArgumentParser(description="Hello Agent")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8090)
    args = parser.parse_args()

    uvicorn.run(app, host=args.host, port=args.port, log_level="info")


if __name__ == "__main__":
    main()
'''

        output_path.write_text(python_content, encoding='utf-8')

        # 同时生成 requirements.txt 文件
        requirements_path = Path(output_dir) / "requirements.txt"
        requirements_content = f'''fastapi>=0.100.0
uvicorn>=0.23.0
'''
        requirements_path.write_text(requirements_content, encoding='utf-8')
        print(f"[AgentConverter] Generated echo server: {output_path}")
        print(f"[AgentConverter] Generated requirements.txt: {requirements_path}")

        return str(output_path)
