[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openjiuwen-runtime-examples-workflow-agent"
version = "0.1.0"
description = "OpenJiuwen Runtime"
requires-python = ">=3.11.4"
dependencies = [
]

[tool.uv]
default-groups = ['dev']

[dependency-groups]
dev = [
    "coverage==7.8.0",
    "pytest==8.3.5",
    "pytest-asyncio==1.2.0",
    "pytest-mock==3.14.0",
    "ruff==0.9.10",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["*.egg-info", "tests"]
include = ["openjiuwen_runtime*"]